version: '3'
services:
  todddo:
    container_name: todddo
    image: ruby:3.1.2
    working_dir: /app
    environment:
      - BUNDLE_PATH=/app/bundle
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: /app/scripts/start.sh

  maildev:
    container_name: todddo-maildev
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
